# This example is from https://docs.google.com/document/d/1cLPGweVEYrVqQvBLJg6sxV-TrE5Rm2MNOBA_cxZP2WU/edit#heading=h.dr88tktf0e99

# Inspired by https://github.com/kubernetes/helm/blob/master/docs/charts.md
# But Kubernetes API style
apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: mungebot
resources:
- deployment.yaml
#Recursive would be similar to kubectl --recursive behavior, extended to look for Kube-manifest.yaml
recursive: false
#Whether PersistentVolumeClaims should be deleted with the other resources
ownPersistentVolumeClaims: true
