
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  go-tests = true

# Necessary to fix panic ... ""
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
name="sigs.k8s.io/controller-runtime"
branch="master"

[[constraint]]
name="k8s.io/kubernetes"
branch="master"

[[override]]
name="k8s.io/api"
branch="master"

[[override]]
name="k8s.io/apiextensions-apiserver"
branch="master"

[[override]]
name="k8s.io/apimachinery"
branch="master"

[[override]]
name="k8s.io/client-go"
branch="master"

[[override]]
name="k8s.io/kube-aggregator"
branch="master"

[[override]]
name="k8s.io/kube-openapi"
branch="master"

[[override]]
name="github.com/russross/blackfriday"
revision="300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
name="github.com/docker/distribution"
revision="edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
name="github.com/imdario/mergo"
revision="6633656539c1639d9d78127b7d47c622b5d7b6dc"
