// Code generated by counterfeiter. DO NOT EDIT.
package testfakes

import (
	"sync"

	"k8s.io/kubectl/pkg/framework/test"
)

type FakeBinPathFinder struct {
	Stub        func(symbolicName string) (binPath string)
	mutex       sync.RWMutex
	argsForCall []struct {
		symbolicName string
	}
	returns struct {
		result1 string
	}
	returnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBinPathFinder) Spy(symbolicName string) (binPath string) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		symbolicName string
	}{symbolicName})
	fake.recordInvocation("BinPathFinder", []interface{}{symbolicName})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(symbolicName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.returns.result1
}

func (fake *FakeBinPathFinder) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeBinPathFinder) ArgsForCall(i int) string {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].symbolicName
}

func (fake *FakeBinPathFinder) Returns(result1 string) {
	fake.Stub = nil
	fake.returns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBinPathFinder) ReturnsOnCall(i int, result1 string) {
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBinPathFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBinPathFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ test.BinPathFinder = new(FakeBinPathFinder).Spy
